"""
snmp_seeds/apc.py — APC/Schneider Electric UPS trap definitions.

Enterprise OID: 1.3.6.1.4.1.318
MIB: PowerNet-MIB (APC)
"""

ENTERPRISE_MAP = [
    {"enterprise_oid": "1.3.6.1.4.1.318",       "vendor": "APC",  "product_family": "UPS/PowerNet"},
    {"enterprise_oid": "1.3.6.1.4.1.318.1.1.1", "vendor": "APC",  "product_family": "Smart-UPS"},
    {"enterprise_oid": "1.3.6.1.4.1.318.1.1.8", "vendor": "APC",  "product_family": "Symmetra"},
]

TRAP_DEFINITIONS = [
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.5",
        "trap_name":          "apcUpsOnBattery",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "critical",
        "category":           "ups",
        "probable_cause":     "Utility/mains power failed. UPS switched to battery operation.",
        "description":        "The APC UPS has switched from utility power to battery backup due to a power outage.",
        "recommended_action": "Investigate cause of power failure. Monitor battery runtime. Prepare for controlled shutdown if power is not restored.",
        "varbind_hints":      {
            "1.3.6.1.4.1.318.1.1.1.2.2.1": "upsAdvBatteryCapacity",
            "1.3.6.1.4.1.318.1.1.1.2.2.3": "upsAdvBatteryRunTimeRemaining",
        },
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.8",
        "trap_name":          "apcUpsReturnedFromBattery",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "info",
        "category":           "ups",
        "probable_cause":     "Utility power restored. UPS returned to normal online operation.",
        "description":        "The APC UPS has returned from battery to normal utility power.",
        "recommended_action": "Informational. Monitor battery for proper recharge.",
        "varbind_hints":      {},
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.4",
        "trap_name":          "apcUpsBatteryLow",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "critical",
        "category":           "ups",
        "probable_cause":     "UPS battery charge is critically low. Power outage is ongoing and runtime is almost exhausted.",
        "description":        "The APC UPS battery has reached a critically low charge level.",
        "recommended_action": "Immediately initiate a controlled shutdown of critical systems. The UPS will shut down imminently.",
        "varbind_hints":      {
            "1.3.6.1.4.1.318.1.1.1.2.2.1": "upsAdvBatteryCapacity",
            "1.3.6.1.4.1.318.1.1.1.2.2.3": "upsAdvBatteryRunTimeRemaining",
        },
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.6",
        "trap_name":          "apcUpsBatteryNeedsReplacement",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "warning",
        "category":           "ups",
        "probable_cause":     "UPS battery has reached end of life and requires replacement.",
        "description":        "The APC UPS has detected that the battery needs replacement.",
        "recommended_action": "Order replacement battery immediately. Replace before next power event. Follow APC battery replacement procedure.",
        "varbind_hints":      {},
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.7",
        "trap_name":          "apcUpsBatteryReplaced",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "info",
        "category":           "ups",
        "probable_cause":     "UPS battery was replaced.",
        "description":        "The APC UPS battery has been replaced.",
        "recommended_action": "Informational. Run a battery test to verify new battery health.",
        "varbind_hints":      {},
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.25",
        "trap_name":          "apcUpsOverload",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "critical",
        "category":           "ups",
        "probable_cause":     "UPS output load exceeded rated capacity.",
        "description":        "The APC UPS is overloaded. Total load exceeds rated VA/W capacity.",
        "recommended_action": "Reduce load by shedding non-critical equipment. Check for unexpected high-draw devices. Consider UPS replacement with higher capacity.",
        "varbind_hints":      {
            "1.3.6.1.4.1.318.1.1.1.4.2.3": "upsAdvOutputLoad",
        },
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.3",
        "trap_name":          "apcUpsDischarged",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "critical",
        "category":           "ups",
        "probable_cause":     "UPS battery fully discharged. Systems may have lost power.",
        "description":        "The APC UPS battery has been completely discharged.",
        "recommended_action": "Assess impact of power loss. Restore utility power and allow UPS to recharge before relying on it again.",
        "varbind_hints":      {},
        "mib_name":           "PowerNet-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.318.0.86",
        "trap_name":          "apcUpsInputLineVoltageProblem",
        "vendor":             "APC",
        "product_family":     "UPS",
        "severity":           "warning",
        "category":           "ups",
        "probable_cause":     "Input line voltage is out of acceptable range (too high or too low).",
        "description":        "The APC UPS has detected an input voltage problem.",
        "recommended_action": "Check utility power quality. Investigate source of voltage irregularities. Consider line conditioning.",
        "varbind_hints":      {
            "1.3.6.1.4.1.318.1.1.1.3.2.1": "upsAdvInputLineVoltage",
        },
        "mib_name":           "PowerNet-MIB",
    },
]
