"""
snmp_seeds/fortinet.py — Fortinet FortiGate trap definitions.

Enterprise OID: 1.3.6.1.4.1.12356
MIB: FORTINET-FORTIGATE-MIB
"""

ENTERPRISE_MAP = [
    {"enterprise_oid": "1.3.6.1.4.1.12356",     "vendor": "Fortinet", "product_family": "FortiGate"},
    {"enterprise_oid": "1.3.6.1.4.1.12356.101",  "vendor": "Fortinet", "product_family": "FortiGate"},
    {"enterprise_oid": "1.3.6.1.4.1.12356.103",  "vendor": "Fortinet", "product_family": "FortiAnalyzer"},
    {"enterprise_oid": "1.3.6.1.4.1.12356.104",  "vendor": "Fortinet", "product_family": "FortiManager"},
]

TRAP_DEFINITIONS = [
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.100",
        "trap_name":          "fgTrapCpuHigh",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "FortiGate CPU utilization exceeded threshold.",
        "description":        "CPU usage has risen above the configured alert threshold.",
        "recommended_action": "Check running processes, active sessions, and UTM inspection load. Consider traffic offloading or hardware upgrade.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.4.1.3": "fgSysCpuUsage"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.101",
        "trap_name":          "fgTrapMemLow",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "FortiGate memory utilization exceeded threshold.",
        "description":        "Available memory has dropped below the configured alert threshold.",
        "recommended_action": "Review memory usage. Reduce UTM features or session table size. Consider hardware upgrade.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.4.1.4": "fgSysMemUsage"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.102",
        "trap_name":          "fgTrapLogDiskFull",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "FortiGate log disk is nearing capacity.",
        "description":        "The log disk has reached or exceeded its configured threshold.",
        "recommended_action": "Archive or clear old logs. Configure log rotation. Consider sending logs to FortiAnalyzer or syslog server.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.103",
        "trap_name":          "fgTrapIntfIPChange",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "config",
        "probable_cause":     "An interface IP address was changed.",
        "description":        "A FortiGate network interface IP address has changed.",
        "recommended_action": "Verify the IP change was intended. Update DNS records and monitoring targets if needed.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.7.2.1.2": "fgIntfName",
            "1.3.6.1.4.1.12356.101.7.2.1.3": "fgIntfIp",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.104",
        "trap_name":          "fgTrapVpnTunUp",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "vpn",
        "probable_cause":     "An IPsec VPN tunnel came up.",
        "description":        "A FortiGate IPsec VPN tunnel has been established.",
        "recommended_action": "Informational. Verify expected VPN peer and traffic flow.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.12.2.1.1.3": "fgVpnTunEntPhase1Name",
            "1.3.6.1.4.1.12356.101.12.2.1.1.4": "fgVpnTunEntPhase2Name",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.105",
        "trap_name":          "fgTrapVpnTunDown",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "vpn",
        "probable_cause":     "An IPsec VPN tunnel went down. Possible causes: peer unreachable, IKE negotiation failure, certificate expired, DPD timeout.",
        "description":        "A FortiGate IPsec VPN tunnel has gone down.",
        "recommended_action": "Check peer gateway connectivity. Review IKE/IPsec logs on both sides. Verify pre-shared keys or certificates are valid.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.12.2.1.1.3": "fgVpnTunEntPhase1Name",
            "1.3.6.1.4.1.12356.101.12.2.1.1.4": "fgVpnTunEntPhase2Name",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.106",
        "trap_name":          "fgTrapHaSwitch",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "system",
        "probable_cause":     "FortiGate HA failover occurred. The primary unit became unavailable and the secondary unit took over.",
        "description":        "A FortiGate HA cluster has performed a failover.",
        "recommended_action": "Investigate why the primary unit failed. Check hardware health, power, and network connectivity of the original primary. Plan maintenance window to restore HA pair.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.107",
        "trap_name":          "fgTrapHaHBFail",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "system",
        "probable_cause":     "FortiGate HA heartbeat failure detected between cluster members.",
        "description":        "HA heartbeat packets are not being received from the peer unit.",
        "recommended_action": "Check HA heartbeat link (dedicated cable or VLAN). Verify both units are powered on. Check for split-brain scenarios.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.108",
        "trap_name":          "fgTrapIpsAnomaly",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "security",
        "probable_cause":     "IPS anomaly detection triggered.",
        "description":        "FortiGate IPS engine detected a traffic anomaly.",
        "recommended_action": "Review IPS logs for source IP and attack signature. Block source if malicious. Update IPS signatures.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.109",
        "trap_name":          "fgTrapIpsSig",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "security",
        "probable_cause":     "IPS signature match detected.",
        "description":        "FortiGate IPS engine matched a known attack signature in traffic.",
        "recommended_action": "Review IPS logs. Identify source and destination. Block or quarantine source IP if confirmed malicious.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.110",
        "trap_name":          "fgTrapAvVirus",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "security",
        "probable_cause":     "Antivirus scan detected malware in traffic.",
        "description":        "FortiGate antivirus engine detected and blocked a virus or malware.",
        "recommended_action": "Check AV logs for source/destination. Quarantine infected endpoint. Run endpoint AV scan. Update AV signatures.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.302",
        "trap_name":          "fgTrapSslVpnLogin",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "vpn",
        "probable_cause":     "SSL VPN user logged in.",
        "description":        "A user has established an SSL VPN session.",
        "recommended_action": "Informational. Verify the login is from an authorized user and expected location.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.303",
        "trap_name":          "fgTrapSslVpnLogout",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "vpn",
        "probable_cause":     "SSL VPN user logged out.",
        "description":        "An SSL VPN session has ended.",
        "recommended_action": "Informational.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── Admin login / logout ────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.201",
        "trap_name":          "fgTrapAdminLogin",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "auth",
        "probable_cause":     "An administrator logged in to the FortiGate management interface.",
        "description":        "Admin login event.",
        "recommended_action": "Verify the login was authorized. Review source IP and time.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.2.1.1": "fgTrapAdminName",
            "1.3.6.1.4.1.12356.101.2.1.2": "fgTrapAdminAddr",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.202",
        "trap_name":          "fgTrapAdminLogout",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "auth",
        "probable_cause":     "An administrator logged out of the FortiGate management interface.",
        "description":        "Admin logout event.",
        "recommended_action": "Informational.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.2.1.1": "fgTrapAdminName",
            "1.3.6.1.4.1.12356.101.2.1.2": "fgTrapAdminAddr",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── System / daemon ─────────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.111",
        "trap_name":          "fgTrapConserveMode",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "hardware",
        "probable_cause":     "FortiGate has entered memory conserve mode due to critically low available memory.",
        "description":        "System entered conserve mode — new sessions may be blocked.",
        "recommended_action": "Free memory by reducing UTM features or active sessions. Consider reboot during maintenance window if condition persists.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.4.1.4": "fgSysMemUsage"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.112",
        "trap_name":          "fgTrapCrash",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "system",
        "probable_cause":     "A FortiGate daemon or process has crashed.",
        "description":        "A daemon on the FortiGate has crashed and may be restarting.",
        "recommended_action": "Check system event logs. Collect crash report. Contact Fortinet TAC if the crash recurs.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── HA ──────────────────────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.113",
        "trap_name":          "fgTrapHaStateChange",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "system",
        "probable_cause":     "The HA role of this FortiGate unit has changed (master/slave).",
        "description":        "HA state transition detected.",
        "recommended_action": "Verify the cluster is stable and both units are synchronized.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── Interface / routing ─────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.114",
        "trap_name":          "fgTrapBgpNeighborStateChange",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "routing",
        "probable_cause":     "A BGP neighbor's session state changed (established/idle/active).",
        "description":        "FortiGate BGP neighbor state change.",
        "recommended_action": "Check BGP peer connectivity and routing table. Verify BGP timers and AS configuration.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.15.1.1.1.2": "fgBgpNeighbor",
            "1.3.6.1.4.1.12356.101.15.1.1.1.3": "fgBgpNeighborState",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.115",
        "trap_name":          "fgTrapPppoeConnectFail",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "link",
        "probable_cause":     "PPPoE connection attempt failed.",
        "description":        "FortiGate failed to establish a PPPoE connection on a WAN interface.",
        "recommended_action": "Check PPPoE credentials, ISP status, and WAN cable/signal.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.7.2.1.2": "fgIntfName"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── Security ────────────────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.116",
        "trap_name":          "fgTrapAvBlock",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "security",
        "probable_cause":     "Antivirus blocked a file transfer.",
        "description":        "FortiGate antivirus blocked a file based on configured AV policy.",
        "recommended_action": "Review AV log entry for filename, user, and source IP.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.117",
        "trap_name":          "fgTrapIpsPkgUpdate",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "system",
        "probable_cause":     "IPS signature database was updated.",
        "description":        "FortiGate successfully updated its IPS signature package.",
        "recommended_action": "Informational. Verify the new signature version in System > FortiGuard.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── DHCP ────────────────────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.118",
        "trap_name":          "fgTrapDhcpLeaseFull",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "system",
        "probable_cause":     "DHCP address pool is exhausted.",
        "description":        "The FortiGate DHCP server address pool is full and cannot lease new addresses.",
        "recommended_action": "Expand the DHCP address range, reduce lease time, or check for IP exhaustion attacks.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── FortiAnalyzer connectivity ──────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.401",
        "trap_name":          "fgTrapFazConnectFail",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "system",
        "probable_cause":     "FortiGate failed to connect to FortiAnalyzer.",
        "description":        "Connection to the configured FortiAnalyzer has failed.",
        "recommended_action": "Verify FortiAnalyzer is reachable from the FortiGate management interface. Check firewall rules and FAZ disk space.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.402",
        "trap_name":          "fgTrapFazDisconnect",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "system",
        "probable_cause":     "FortiGate disconnected from FortiAnalyzer.",
        "description":        "An established connection to FortiAnalyzer was lost.",
        "recommended_action": "Check FortiAnalyzer availability. Review network path between FortiGate and FortiAnalyzer.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── SLB (Server Load Balancing) ─────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.501",
        "trap_name":          "fgTrapSlbRealServerDown",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "system",
        "probable_cause":     "A real server in a FortiGate SLB virtual server pool has gone down.",
        "description":        "FortiGate SLB health check: real server is not responding.",
        "recommended_action": "Check the health of the real server. Review SLB health check logs.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.14.2.1.1.2": "fgSlbRealServerName",
            "1.3.6.1.4.1.12356.101.14.2.1.1.3": "fgSlbRealServerIp",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.502",
        "trap_name":          "fgTrapSlbRealServerUp",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "system",
        "probable_cause":     "A real server in a FortiGate SLB virtual server pool has recovered.",
        "description":        "FortiGate SLB health check: real server is responding again.",
        "recommended_action": "Informational. Verify traffic is being balanced correctly.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.14.2.1.1.2": "fgSlbRealServerName",
            "1.3.6.1.4.1.12356.101.14.2.1.1.3": "fgSlbRealServerIp",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── WiFi / FortiWiFi (Wireless Controller) ──────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.601",
        "trap_name":          "fgTrapWcApDown",
        "vendor":             "Fortinet",
        "product_family":     "FortiWiFi/FortiAP",
        "severity":           "critical",
        "category":           "link",
        "probable_cause":     "A managed FortiAP has disconnected from the wireless controller.",
        "description":        "FortiAP lost connection to the FortiGate wireless controller.",
        "recommended_action": "Check FortiAP power and physical connection. Verify management VLAN reachability.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.18.2.1.2": "fgWcApName",
            "1.3.6.1.4.1.12356.101.18.2.1.3": "fgWcApIpAddress",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.602",
        "trap_name":          "fgTrapWcApUp",
        "vendor":             "Fortinet",
        "product_family":     "FortiWiFi/FortiAP",
        "severity":           "info",
        "category":           "link",
        "probable_cause":     "A managed FortiAP has connected to the wireless controller.",
        "description":        "FortiAP has joined the FortiGate wireless controller.",
        "recommended_action": "Informational. Verify AP radio configuration and associated SSIDs.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.18.2.1.2": "fgWcApName",
            "1.3.6.1.4.1.12356.101.18.2.1.3": "fgWcApIpAddress",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    # ── Interface policy ────────────────────────────────────────────────────
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.119",
        "trap_name":          "fgTrapIntfPolicyChange",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "config",
        "probable_cause":     "A firewall policy applied to an interface was changed.",
        "description":        "FortiGate interface policy change event.",
        "recommended_action": "Verify the policy change was authorized. Review audit logs.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.7.2.1.2": "fgIntfName"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
]
