"""
snmp_seeds/fortinet.py — Fortinet FortiGate trap definitions.

Enterprise OID: 1.3.6.1.4.1.12356
MIB: FORTINET-FORTIGATE-MIB
"""

ENTERPRISE_MAP = [
    {"enterprise_oid": "1.3.6.1.4.1.12356",     "vendor": "Fortinet", "product_family": "FortiGate"},
    {"enterprise_oid": "1.3.6.1.4.1.12356.101",  "vendor": "Fortinet", "product_family": "FortiGate"},
    {"enterprise_oid": "1.3.6.1.4.1.12356.103",  "vendor": "Fortinet", "product_family": "FortiAnalyzer"},
    {"enterprise_oid": "1.3.6.1.4.1.12356.104",  "vendor": "Fortinet", "product_family": "FortiManager"},
]

TRAP_DEFINITIONS = [
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.100",
        "trap_name":          "fgTrapCpuHigh",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "FortiGate CPU utilization exceeded threshold.",
        "description":        "CPU usage has risen above the configured alert threshold.",
        "recommended_action": "Check running processes, active sessions, and UTM inspection load. Consider traffic offloading or hardware upgrade.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.4.1.3": "fgSysCpuUsage"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.101",
        "trap_name":          "fgTrapMemLow",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "FortiGate memory utilization exceeded threshold.",
        "description":        "Available memory has dropped below the configured alert threshold.",
        "recommended_action": "Review memory usage. Reduce UTM features or session table size. Consider hardware upgrade.",
        "varbind_hints":      {"1.3.6.1.4.1.12356.101.4.1.4": "fgSysMemUsage"},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.102",
        "trap_name":          "fgTrapLogDiskFull",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "FortiGate log disk is nearing capacity.",
        "description":        "The log disk has reached or exceeded its configured threshold.",
        "recommended_action": "Archive or clear old logs. Configure log rotation. Consider sending logs to FortiAnalyzer or syslog server.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.103",
        "trap_name":          "fgTrapIntfIPChange",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "config",
        "probable_cause":     "An interface IP address was changed.",
        "description":        "A FortiGate network interface IP address has changed.",
        "recommended_action": "Verify the IP change was intended. Update DNS records and monitoring targets if needed.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.7.2.1.2": "fgIntfName",
            "1.3.6.1.4.1.12356.101.7.2.1.3": "fgIntfIp",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.104",
        "trap_name":          "fgTrapVpnTunUp",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "vpn",
        "probable_cause":     "An IPsec VPN tunnel came up.",
        "description":        "A FortiGate IPsec VPN tunnel has been established.",
        "recommended_action": "Informational. Verify expected VPN peer and traffic flow.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.12.2.1.1.3": "fgVpnTunEntPhase1Name",
            "1.3.6.1.4.1.12356.101.12.2.1.1.4": "fgVpnTunEntPhase2Name",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.105",
        "trap_name":          "fgTrapVpnTunDown",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "vpn",
        "probable_cause":     "An IPsec VPN tunnel went down. Possible causes: peer unreachable, IKE negotiation failure, certificate expired, DPD timeout.",
        "description":        "A FortiGate IPsec VPN tunnel has gone down.",
        "recommended_action": "Check peer gateway connectivity. Review IKE/IPsec logs on both sides. Verify pre-shared keys or certificates are valid.",
        "varbind_hints":      {
            "1.3.6.1.4.1.12356.101.12.2.1.1.3": "fgVpnTunEntPhase1Name",
            "1.3.6.1.4.1.12356.101.12.2.1.1.4": "fgVpnTunEntPhase2Name",
        },
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.106",
        "trap_name":          "fgTrapHaSwitch",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "system",
        "probable_cause":     "FortiGate HA failover occurred. The primary unit became unavailable and the secondary unit took over.",
        "description":        "A FortiGate HA cluster has performed a failover.",
        "recommended_action": "Investigate why the primary unit failed. Check hardware health, power, and network connectivity of the original primary. Plan maintenance window to restore HA pair.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.107",
        "trap_name":          "fgTrapHaHBFail",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "system",
        "probable_cause":     "FortiGate HA heartbeat failure detected between cluster members.",
        "description":        "HA heartbeat packets are not being received from the peer unit.",
        "recommended_action": "Check HA heartbeat link (dedicated cable or VLAN). Verify both units are powered on. Check for split-brain scenarios.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.108",
        "trap_name":          "fgTrapIpsAnomaly",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "security",
        "probable_cause":     "IPS anomaly detection triggered.",
        "description":        "FortiGate IPS engine detected a traffic anomaly.",
        "recommended_action": "Review IPS logs for source IP and attack signature. Block source if malicious. Update IPS signatures.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.109",
        "trap_name":          "fgTrapIpsSig",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "warning",
        "category":           "security",
        "probable_cause":     "IPS signature match detected.",
        "description":        "FortiGate IPS engine matched a known attack signature in traffic.",
        "recommended_action": "Review IPS logs. Identify source and destination. Block or quarantine source IP if confirmed malicious.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.110",
        "trap_name":          "fgTrapAvVirus",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "critical",
        "category":           "security",
        "probable_cause":     "Antivirus scan detected malware in traffic.",
        "description":        "FortiGate antivirus engine detected and blocked a virus or malware.",
        "recommended_action": "Check AV logs for source/destination. Quarantine infected endpoint. Run endpoint AV scan. Update AV signatures.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.302",
        "trap_name":          "fgTrapSslVpnLogin",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "vpn",
        "probable_cause":     "SSL VPN user logged in.",
        "description":        "A user has established an SSL VPN session.",
        "recommended_action": "Informational. Verify the login is from an authorized user and expected location.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.12356.101.2.0.303",
        "trap_name":          "fgTrapSslVpnLogout",
        "vendor":             "Fortinet",
        "product_family":     "FortiGate",
        "severity":           "info",
        "category":           "vpn",
        "probable_cause":     "SSL VPN user logged out.",
        "description":        "An SSL VPN session has ended.",
        "recommended_action": "Informational.",
        "varbind_hints":      {},
        "mib_name":           "FORTINET-FORTIGATE-MIB",
    },
]
