"""
snmp_seeds/juniper.py — Juniper Networks trap definitions.

Enterprise OID: 1.3.6.1.4.1.2636
MIBs: JUNIPER-CHASSIS-DEFINES-MIB, JUNIPER-ALARM-MIB, mib-jnx-traps
"""

ENTERPRISE_MAP = [
    {"enterprise_oid": "1.3.6.1.4.1.2636",       "vendor": "Juniper", "product_family": "JunOS"},
    {"enterprise_oid": "1.3.6.1.4.1.2636.3",      "vendor": "Juniper", "product_family": "JunOS Routing"},
    {"enterprise_oid": "1.3.6.1.4.1.2636.4",      "vendor": "Juniper", "product_family": "JunOS Chassis"},
]

TRAP_DEFINITIONS = [
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.1.0.1",
        "trap_name":          "jnxYellowAlarmState",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "warning",
        "category":           "hardware",
        "probable_cause":     "Juniper chassis yellow (minor) alarm is active.",
        "description":        "A yellow (minor) alarm condition has been detected on the Juniper chassis.",
        "recommended_action": "Review chassis alarm details via 'show chassis alarms'. Address the underlying minor fault.",
        "varbind_hints":      {
            "1.3.6.1.4.1.2636.3.4.2.2.1.1": "jnxYellowAlarmCount",
            "1.3.6.1.4.1.2636.3.4.2.2.1.2": "jnxYellowAlarmLastChange",
        },
        "mib_name":           "JUNIPER-ALARM-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.1.0.2",
        "trap_name":          "jnxYellowAlarmClear",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "info",
        "category":           "hardware",
        "probable_cause":     "Juniper chassis yellow (minor) alarm cleared.",
        "description":        "The yellow (minor) alarm condition on the Juniper chassis has been cleared.",
        "recommended_action": "Informational. Verify normal operation.",
        "varbind_hints":      {},
        "mib_name":           "JUNIPER-ALARM-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.1.0.3",
        "trap_name":          "jnxRedAlarmState",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "critical",
        "category":           "hardware",
        "probable_cause":     "Juniper chassis red (major) alarm is active. A critical hardware fault has been detected.",
        "description":        "A red (major) alarm condition has been detected on the Juniper chassis.",
        "recommended_action": "Run 'show chassis alarms' and 'show chassis hardware' immediately. Contact Juniper JTAC if hardware replacement is needed.",
        "varbind_hints":      {
            "1.3.6.1.4.1.2636.3.4.2.3.1.1": "jnxRedAlarmCount",
            "1.3.6.1.4.1.2636.3.4.2.3.1.2": "jnxRedAlarmLastChange",
        },
        "mib_name":           "JUNIPER-ALARM-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.1.0.4",
        "trap_name":          "jnxRedAlarmClear",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "info",
        "category":           "hardware",
        "probable_cause":     "Juniper chassis red (major) alarm cleared.",
        "description":        "The red (major) alarm condition on the Juniper chassis has been cleared.",
        "recommended_action": "Informational. Verify full hardware health.",
        "varbind_hints":      {},
        "mib_name":           "JUNIPER-ALARM-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.14.0.1",
        "trap_name":          "jnxSonetSectionLOS",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "critical",
        "category":           "link",
        "probable_cause":     "Loss of Signal detected on SONET interface.",
        "description":        "SONET section Loss Of Signal (LOS) alarm raised.",
        "recommended_action": "Check fiber physical connectivity. Verify optical signal levels. Contact carrier if circuit issue.",
        "varbind_hints":      {},
        "mib_name":           "JUNIPER-SONET-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.5.0.1",
        "trap_name":          "jnxPowerSupplyFailed",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "critical",
        "category":           "hardware",
        "probable_cause":     "Juniper chassis power supply failure detected.",
        "description":        "A power supply unit in the Juniper chassis has failed.",
        "recommended_action": "Replace failed PSU immediately. Verify redundant PSU is operational. Schedule emergency maintenance.",
        "varbind_hints":      {
            "1.3.6.1.4.1.2636.3.1.15.1.5": "jnxContainerDescr",
        },
        "mib_name":           "JUNIPER-CHASSIS-DEFINES-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.5.0.2",
        "trap_name":          "jnxFanFailed",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "critical",
        "category":           "hardware",
        "probable_cause":     "Juniper chassis fan failure detected.",
        "description":        "A fan module in the Juniper chassis has failed.",
        "recommended_action": "Replace failed fan tray immediately. Monitor chassis temperature. Schedule urgent maintenance.",
        "varbind_hints":      {},
        "mib_name":           "JUNIPER-CHASSIS-DEFINES-MIB",
    },
    {
        "trap_oid":           "1.3.6.1.4.1.2636.4.5.0.3",
        "trap_name":          "jnxFpcFailed",
        "vendor":             "Juniper",
        "product_family":     "JunOS",
        "severity":           "critical",
        "category":           "hardware",
        "probable_cause":     "Juniper Flexible PIC Concentrator (FPC/line card) failure.",
        "description":        "A line card (FPC) in the Juniper chassis has failed.",
        "recommended_action": "Check FPC status with 'show chassis fpc'. Reseat or replace the FPC. Contact JTAC for hardware support.",
        "varbind_hints":      {
            "1.3.6.1.4.1.2636.3.1.15.1.5": "jnxContainerDescr",
        },
        "mib_name":           "JUNIPER-CHASSIS-DEFINES-MIB",
    },
]
